version: '3.7'

services:
  express-api-mongodb-boilerplate:
    image: express-api-mongodb-boilerplate
    container_name: express-api-mongodb-boilerplate
    build: .docker/development
    command: npm run start:dev
    environment:
      NODE_ENV: development
    volumes:
      - .:/api
